Move mbedtls_ssl_handshake_key_derivation from ee prepare to sh post
hannestschofenig/mbedtls pull request #123
Opened 2021-01-13 19:05 UTC by lhuang04

Summary:
According to https://tools.ietf.org/html/rfc8446#appendix-A.1, handshake
secret could be set after client receives server hello. Although it
sound not much different between `ssl_encrypted_extensions_prepare` and
`ssl_server_hello_postprocess`. In some transport, such as QUIC, we
won't able to receive Encrypted Extension msg without handshake secret.
We suggest to move the `mbedtls_ssl_handshake_key_derivation` from
`ssl_encrypted_extensions_prepare` to `ssl_server_hello_postprocess`.

Test Plan:
`ssl-opt.sh`

Reviewers:

Subscribers:

Tasks:

Tags:

2021-01-14 06:59 UTC, hanno-arm commented on library/ssl_tls13_client.c
>  #if defined(MBEDTLS_SSL_PROTO_DTLS)
We should also move the DTLS 1.3 specific code here.

2021-01-14 07:00 UTC, hanno-arm commented on library/ssl_tls13_client.c
> +    ssl->session_in = ssl->session_negotiate;
Pre-existing defect worth fixing along the way: We must zeroize the sensitive stack variable `mbedtls_ssl_traffic_keys` here, using `mbedtls_platform_zeroize()`.

2021-01-14 07:01 UTC, hanno-arm requested changes
Looks good to me except for two things:
* Even if we don't actively work on the DTLS 1.3 code at the moment, we should keep the TLS 1.3 and DTLS 1.3 key switching code paths in sync. In particular, we should move the epoch increase to the ServerHello postprocessing, too.
* Pre-existing but worth fixing: We leak the key material on the stack in the previous and current version of the key switching code.

2021-01-14 19:21 UTC, lhuang04 commented
@hanno-arm , updated based on your comments. Could you take another look?

2021-01-15 06:07 UTC, hanno-arm commented on library/ssl_tls13_client.c
> +    int ret;
```suggestion
    int ret;
    mbedtls_ssl_key_set traffic_keys;
```

2021-01-15 06:07 UTC, hanno-arm commented on library/ssl_tls13_client.c
> +
```suggestion
```

2021-01-15 06:08 UTC, hanno-arm commented on library/ssl_tls13_client.c
> +    int ret;
While no longer strictly necessary since we officially require C99, let's try to stick to having declarations at the beginning of scopes.

2021-01-15 06:09 UTC, hanno-arm approved these changes
Thanks @lhuang04 - looks good to me.

2021-01-15 06:09 UTC, merged