Simplify MBEDTLS_SSL_TLS13_COMPATIBILITY_MODE  in `ssl_server_hello_parse` and `ssl_hrr_parse`
hannestschofenig/mbedtls pull request #208
Opened 2021-04-20 14:42 UTC by lhuang04

Summary:
Simplify MBEDTLS_SSL_TLS13_COMPATIBILITY_MODE  in
`ssl_server_hello_parse` and `ssl_hrr_parse`.
When MBEDTLS_SSL_TLS13_COMPATIBILITY_MODE is on, the
[ssl->session_negotiate->id_len will be non zero](https://github.com/hannestschofenig/mbedtls/blob/tls13-prototype/library/ssl_tls13_client.c#L1512).
The
[else](https://github.com/hannestschofenig/mbedtls/blob/tls13-prototype/library/ssl_tls13_client.c#L3097-L3109) block is the same as [if](https://github.com/hannestschofenig/mbedtls/blob/tls13-prototype/library/ssl_tls13_client.c#L3074-L3093) block when
`ssl->session_negotiate->id_len` is 0.
So we could remove the else block in `ssl_server_hello_parse`. Same
thing applies to `ssl_hrr_parse`.

Test Plan:
`tests/ssl-opt.sh` when MBEDTLS_SSL_TLS13_COMPATIBILITY_MODE is on and
off.

Reviewers:

Subscribers:

Tasks:

Tags:

2021-04-20 16:00 UTC, hanno-arm requested changes
Thanks for spotting this @lhuang04, I agree with your analysis. 

Would you mind further improving this block of code while we're at it? For example:
* Having only a single branch for a mismatching `legacy_session_id_echo`
* Adjusting style
* Perhaps finding a way to share this part of ServerHello and HRR parsing

2021-04-21 17:10 UTC, lhuang04 commented
@hanno-arm , I added a commit to share the implementation between ServerHello and HRR parsing.
Could you elaborate about having only a single branch for a mismatching legacy_session_id_echo?
Do you mean have check like this?
```
if( ssl->session_negotiate->id_len != **buf or memcmp( ssl->session_negotiate->id, *buf, ssl->session_negotiate->id_len ) != 0 ) {
// mismatch
// return failure
}
```

2021-04-26 07:35 UTC, hanno-arm commented
@lhuang04 Thank you for the update. I took the liberty to push some minor style fixes, and add bounds checking.

2021-04-26 11:48 UTC, lhuang04 commented
@hanno-arm , thanks for your additional fix. Looks good to me.

2021-04-26 12:16 UTC, merged