Add functions to parse NST extensions.
hannestschofenig/mbedtls pull request #213
Opened 2021-04-23 18:36 UTC by zhihan

Add functions to parse extensions in NewSessionTicket.

2021-04-26 13:07 UTC, hannestschofenig commented
Do we need to include this code only when enabling the ticket support?

2021-04-26 19:11 UTC, zhihan commented
The field is under 
```
#if defined MBEDTLS_SSL_PROTO_TLS1_3_EXPERIMENTAL && MBEDTLS_SSL_NEW_SESSION_TICKET
```
And the function is under
```
#if defined(MBEDTLS_SSL_NEW_SESSION_TICKET) && defined(MBEDTLS_SSL_CLI_C)
```

2021-04-27 04:21 UTC, hanno-arm requested changes
Thanks @zhihan, this is a valuable addition. 

The trivial thing first: Could you adjust the PR to use Mbed TLS' coding style?

2021-04-27 12:32 UTC, zhihan commented
Formatted to mbedtls's coding style.

2021-07-22 07:09 UTC, hanno-arm commented
I rebased this on top of `tls13-prototype` after @lhuang04's https://github.com/hannestschofenig/mbedtls/pull/257 was merged.

2021-07-22 07:16 UTC, hanno-arm commented
@zhihan Can you add the test you describe in the PR description to `ssl-opt.sh`?

2021-07-22 07:16 UTC, hanno-arm requested changes
LGTM, but we should have a test in `ssl-opt.sh`.

2021-07-22 07:18 UTC, hanno-arm approved these changes
Changed my mind. The PR was open long enough, and we can track the test enhancement separately: https://github.com/hannestschofenig/mbedtls/issues/304

2021-07-22 07:18 UTC, merged