Fix for review of ssl_read_certificate_verify_parse
hannestschofenig/mbedtls pull request #258
Opened 2021-05-06 18:10 UTC by lhuang04

Summary: Review for #184 
* Remove empty line
* Remove out-of-date comments

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags:

Notes:
* Pull requests cannot be accepted until the PR follows the [contributing guidelines](../CONTRIBUTING.md). In particular, each commit must have at least one `Signed-off-by:` line from the committer to certify that the contribution is made under the terms of the [Developer Certificate of Origin](../dco.txt).
* This is just a template, so feel free to use/remove the unnecessary things
## Description
A few sentences describing the overall goals of the pull request's commits.

## Status
**READY/IN DEVELOPMENT/HOLD**

## Requires Backporting
When there is a bug fix, it should be backported to all maintained and supported branches.
Changes do not have to be backported if:
- This PR is a new feature\enhancement
- This PR contains changes in the API. If this is true, and there is a need for the fix to be backported, the fix should be handled differently in the legacy branch

Yes | NO  
Which branch?

## Migrations
If there is any API change, what's the incentive and logic for it.

YES | NO

## Additional comments
Any additional information that could be of interest

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

2021-05-07 05:46 UTC, hanno-arm commented on library/ssl_tls13_generic.c
>      switch ( signature_scheme ) {
Style: No space after `switch`

2021-05-07 05:47 UTC, hanno-arm commented on library/ssl_tls13_generic.c
>      switch ( signature_scheme ) {
Style: Some lines below are overly long.

2021-05-07 06:04 UTC, hanno-arm requested changes
Thank you @lhuang04 

* The code uses a case distinction for SHA-256 vs. SHA-384, which should be replaced by the use of the generic hash API `mbedtls_md_xxx()`.
* As part of this review, we should also consider `mbedtls_ssl_create_verify_structure()`, which needs some rework. For example, the labels used therein could be moved to the label list in `ssl_tls13_keys.h`, and there are some 'magic numbers' in there which should either be explained in comments or, preferably, replaced by suitable macros. Also, the function being static, it should be named `ssl_xxx()` not `mbedtls_ssl_xxx()`.
* Some style issues, e.g. spacing and overly long lines, also in `ssl_certificate_verify_coordinate()`. Could you go over all functions related to CertificateVerify and make sure they adhere to the Mbed TLS style?
* The logic around missing certificates in `ssl_certificate_verify_coordinate()` isn't clear to me. I would expect the function to either skip the write if no certificate is present, or make the check an assertion rather than a possible failure. Could you take a look?

2021-05-07 19:34 UTC, lhuang04 commented
@hanno-arm , could you elaborate your points regarding to `ssl_certificate_verify_coordinate `? This PR handles read certificate verify for #184. [ssl_certificate_verify_coordinate](https://github.com/hannestschofenig/mbedtls/blob/tls13-prototype/library/ssl_tls13_generic.c#L586-L589) is used for write certificate verify, it can be handled in #186.

2021-05-12 13:57 UTC, lhuang04 commented
@hanno-arm , could you check again? I should have address most of the review comments except those for #186

2021-05-14 10:24 UTC, hanno-arm commented on library/ssl_tls13_generic.c
> +    size_t i = 64;
Give this a descriptive name. E.g.:
```c
uint8_t const verify_padding_val = 64;
size_t const verify_padding_len = 32;
size_t i = 0;
memset( verify_buffer, verify_padding_val, verify_padding_len );
i += verify_padding_len;
```

2021-05-14 10:26 UTC, hanno-arm commented on library/ssl_tls13_generic.c
> + * This results in a total size of
This calculation should be moved to the definition of `MBEDTLS_SSL_VERIFY_STRUCT_MAX_SIZE`, which should be referred here.

2021-05-14 10:27 UTC, hanno-arm commented on library/ssl_tls13_generic.c
> +    switch( signature_scheme ) {
```suggestion
    switch( signature_scheme ) 
    {
```

2021-05-14 10:28 UTC, hanno-arm commented on library/ssl_tls13_keys.h
>      sizeof(mbedtls_ssl_tls1_3_labels.LABEL)
Minor: Move this past the new def'n of `MBEDTLS_SSL_TLS1_3_LBL_LEN` and reuse the latter here.

2021-05-14 10:34 UTC, hanno-arm commented on library/ssl_tls13_generic.c
> +    if( ssl->session_negotiate->key_exchange !=
Here we can use the helper `mbedtls_ssl_tls13_key_exchange_with_psk()` instead.

2021-05-14 10:35 UTC, hanno-arm requested changes
Thank you @lhuang04 for the changes!

A few smaller points remain as indicated in the comments.

2021-05-17 16:47 UTC, lhuang04 commented
@hanno-arm , addressed review comments, could you check again?

2021-05-18 04:55 UTC, hanno-arm commented on library/ssl_tls13_generic.c
> +    size_t i = 64;
@lhuang04 Sorry, I might not have been clear: I meant to give a name to the `64`, not necessarily change the name of `i`.

2021-05-18 05:55 UTC, hanno-arm approved these changes

2021-05-18 05:55 UTC, merged