[0-RTT] Reuse mbedtls_ssl_write() for sending early data
hannestschofenig/mbedtls pull request #271
Opened 2021-05-24 19:48 UTC by zhihan

This PR changes the API for sending early data on the client side. It deprecates the `mbedtls_ssl_set_early_data()` method and reuses `mbedtls_ssl_write()` method for sending early data.

## Changes proposed

1. Add an error code `MBEDTLS_ERR_SSL_HANDSHAKE_EARLY_RETURN` for early return. Handshake returns with this error indicating the user can start sending early data. Calling `mbedtls_ssl_handshake()` again will continue the handshake. This pattern is similar to the handling of `NewSessionTicket`.  
1. Rename `MBEDTLS_SSL_EARLY_DATA_ON|OFF` to `MBEDTLS_SSL_EARLY_DATA_STATE_DISABLED |ON|OFF` as these values represent the *state* of the client, rather than a configuration. When early data is enabled, the early_data state is initially ON, it will be turned to OFF if early data is rejected, a HRR is received, or max_early_data is reached (to add).

## Status
**READY**

## Requires Backporting
NO  

## Migrations

## Additional comments
Any additional information that could be of interest

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

2021-05-24 19:49 UTC, zhihan commented
This PR is meant to address https://github.com/hannestschofenig/mbedtls/issues/234

2021-05-26 04:39 UTC, hanno-arm commented
@zhihan Could you rebase this PR on top of the recent `tls13-prototype`?

2021-05-26 04:39 UTC, hanno-arm requested changes
Needs rebasing after merge of #268

2021-08-27 01:08 UTC, zhihan commented
Superseded by #368

2021-08-27 01:08 UTC, closed without merging