Review fix for  #220 certificate request parsing
hannestschofenig/mbedtls pull request #278
Opened 2021-06-01 18:42 UTC by lhuang04

#220. Review of the following functions:
* ssl_certificate_request_parse
* mbedtls_ssl_parse_signature_algorithms_ext

2021-06-02 14:21 UTC, zhihan commented on library/ssl_tls13_client.c
> +                    MBEDTLS_SSL_DEBUG_MSG( 1,
Should this be `MBEDTLS_SSL_DEBUG_RET`?

2021-06-02 14:26 UTC, zhihan commented on library/ssl_tls13_generic.c
> +    uint32_t i = 0; /* iterate through received_signature_schemes_list */
Wondering: should we rename `i` to something more meaningful, like `num_of_matched_hashes`?

2021-06-02 14:28 UTC, zhihan commented on library/ssl_tls13_generic.c
> +            ( "malloc failed in mbedtls_ssl_parse_signature_algorithms_ext( )" ) );
Not sure if it matters, but we are calling `calloc` instead of `malloc`.

2021-06-07 14:37 UTC, hannestschofenig commented
Looks also good to me.

2021-06-08 04:46 UTC, hanno-arm commented on library/ssl_tls13_generic.c
> +                ssl->handshake->received_signature_schemes_list[common_idx] = signature_scheme;
```suggestion
                ssl->handshake->received_signature_schemes_list[common_idx] = 
                                            signature_scheme;
```

2021-06-08 04:53 UTC, hanno-arm commented on library/ssl_tls13_generic.c
Duplicated extensions are not permitted in TLS 1.3, so it shouldn't happen that `received_signature_schemes_list` is not `NULL`. I'd suggest to either remove this check or turn it into an assertion.

2021-06-08 04:53 UTC, hanno-arm commented on library/ssl_tls13_generic.c
It's a separate issue to check the state of the rejection of duplicated extensions.

2021-06-08 04:54 UTC, hanno-arm commented on library/ssl_tls13_generic.c
> +        mbedtls_calloc( num_supported_hashes + 1, sizeof( uint32_t ) );
Instead of a short dyamically sized heap allocated buffer, I suggest that we choose a static compile-time bound on the size here.

2021-06-08 04:55 UTC, hanno-arm requested changes
Thanks @lhuang04 for your work on this. The main request for further improvement is the removal of the heap allocated buffer for the peer provided signature scheme list. Could you work on that?

2021-06-14 12:25 UTC, lhuang04 commented
@hanno-arm , I push a new [commit](https://github.com/hannestschofenig/mbedtls/pull/278/commits/8e75907633022ea85190ce11ceb68be41ef57fbf) for `received_signature_schemes_list`. 
Looks like we could remove `received_signature_schemes_list` completely since it is only used to select signature from `mbedtls_ssl_own_key` which is always the pre-configured key in current TLS 1.3 code.
Could you check if this works? If not, I can go back, and just make the `received_signature_schemes_list` non-heap allocated.

2021-06-18 04:32 UTC, hanno-arm requested changes
Thank you @lhuang04 for your study.

The code looks functionally fine, but I'm uncomfortable with it at the moment because (a) not every handshake uses a server-side certificate. If we don't need one, we don't have to check `own_key()`. (b) We might want to support multiple certificates at some point.

My suggestion would be as follows:
* Revert to a statically allocated `received_signature_schemes_list` as a start.
* Identify (and reflect whether it looks right) the place where the server makes its decisions regarding which key agreement and ciphersuite to use. It is at this point where we should consult the extensions sent by the client, e.g. to see whether we want to use a PSK-based or certificate-based ciphersuite. And if no PSK-based ciphersuite is possible, the server needs to check whether it actually has a suitable certificate, and remember its choice. If we don't have a suitable certificate, we should fail straight away, not just at the time of `CertificateWrite`. If we find that we do have a suitable certificate, we don't need `received_signature_schemes_list` after that anymore.

2021-06-21 12:06 UTC, lhuang04 commented
@hanno-arm , I reverted to a statically allocated received_signature_schemes_list. Could you take a look? I can follow up your second point after checking `received_signature_schemes_list` in a separate PR.

2021-06-24 05:09 UTC, hanno-arm requested changes
I am fine with the change regarding the static allocation of the signature scheme list.

However, looking closer at the code, I'm afraid there is much more that needs changing before we can consider #220 done. 

The signature-algorithms extensions contains lists of pairs of signature algorithms and hash algorithms. However, both the `signature_algorithms` extensions writer and parser treat it as a list of Mbed TLS' internal hash identifiers of type `mbedtls_md_type_t` configured via `mbedtls_ssl_conf_sig_hashes()`. This would never work, where it not for the example program `ssl_server2` using `mbedtls_ssl_conf_sig_hashes()` incorrectly by not passing a list of hash-identifiers, but signature-hash pairs.

I'll need to think about how to best clean this up... I'd appreciate any input.

2021-06-24 05:11 UTC, hanno-arm commented
I suggest we merge this PR anyhow, as it's an improvement, and we can open subsequent PRs to address other aspects of #220 - but we can't close it yet.

2021-06-24 05:12 UTC, hanno-arm approved these changes
Change LGTM - subsequent work on #220 left for further PRs.

2021-06-24 05:12 UTC, merged

2021-06-24 13:32 UTC, lhuang04 commented
@hanno-arm , I agreed. I will keep #220 open, and follow up with additional PR for the remaining issues.