Only use one single ciphersuite if 0-rtt is actually enabled
hannestschofenig/mbedtls pull request #281
Opened 2021-06-04 15:22 UTC by zhihan

In the original code, we break out of the loop if the compiler flag is set. It reads wrong to me. I think we should limit the behavior to where 0-RTT is enabled in the configuration and the handshake is set up for resumption.

2021-06-07 14:24 UTC, hannestschofenig commented
Looks good to me.

2021-06-18 04:06 UTC, hanno-arm requested changes
Thank you @zhihan, it looks good to me. However, could you add a test to `ssl-opt.sh` to check the behaviour? It should be easy by grepping for two distinct ciphersuites in the output.

2021-06-18 19:15 UTC, zhihan commented on tests/ssl-opt.sh
> +        -s "found early_data extension"                 \
Sorry, this was added by my editor: \tab becomes four spaces.

2021-06-18 19:16 UTC, zhihan commented on library/ssl_tls13_client.c
> +            break;
Remove the check for resumption, this condition should be guarded by early_data alone.

2021-06-18 19:16 UTC, zhihan commented
> Thank you @zhihan, it looks good to me. However, could you add a test to `ssl-opt.sh` to check the behaviour? It should be easy by grepping for two distinct ciphersuites in the output.

Added tests.

2021-06-24 05:20 UTC, hanno-arm approved these changes
LGTM

2021-06-24 05:20 UTC, merged