fix unused-function warning
hannestschofenig/mbedtls pull request #299
Opened 2021-07-20 10:24 UTC by yuhaoth

remove unused-function warning . These functions are not used.

And ssl-opt.sh test pass

2021-07-22 06:35 UTC, hanno-arm approved these changes

2021-07-22 06:36 UTC, hanno-arm requested changes
Those functions are used in a specific configuration of MPS: `TEST_SUITE_MPS_NO_SSL`. They cannot be removed. We instead require appropriate compile-time guards.

2021-07-27 06:15 UTC, yuhaoth commented
> 
> 
> Those functions are used in a specific configuration of MPS: `TEST_SUITE_MPS_NO_SSL`. They cannot be removed. We instead require appropriate compile-time guards.

Done.

2021-07-29 09:21 UTC, hanno-arm approved these changes

2021-07-29 09:21 UTC, merged