Postquantum
hannestschofenig/mbedtls pull request #331
Opened 2021-08-02 21:43 UTC by brett-warren-arm

Notes:
* Pull requests cannot be accepted until the PR follows the [contributing guidelines](../CONTRIBUTING.md). In particular, each commit must have at least one `Signed-off-by:` line from the committer to certify that the contribution is made under the terms of the [Developer Certificate of Origin](../dco.txt).
* This is just a template, so feel free to use/remove the unnecessary things
## Description
A few sentences describing the overall goals of the pull request's commits.

## Status
**READY/IN DEVELOPMENT/HOLD**

## Requires Backporting
When there is a bug fix, it should be backported to all maintained and supported branches.
Changes do not have to be backported if:
- This PR is a new feature\enhancement
- This PR contains changes in the API. If this is true, and there is a need for the fix to be backported, the fix should be handled differently in the legacy branch

Yes | NO  
Which branch?

## Migrations
If there is any API change, what's the incentive and logic for it.

YES | NO

## Additional comments
Any additional information that could be of interest

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

2021-08-03 05:00 UTC, hanno-arm commented
Hi @brett-warren-arm, thanks! Can you add a brief description of what's going on the in the PR?

2021-08-03 08:16 UTC, brett-warren-arm commented
**As described in the commit message:**

SSUE: liboqs currently has to be bulit first manually:

	ninja liboqs
	(then whatever commands you desired after)

This is because liboqs.a has to exist, otherwise cmake will
complain about it not existing.

**To elaborate:**

This is where the library is linked,

```
    if(TARGET liboqs)
        add_dependencies(${mbedcrypto_target} PUBLIC liboqs)
	target_link_libraries(${mbedcrypto_target} PUBLIC ${CMAKE_BINARY_DIR}/lib/liboqs.a)
    endif()
```

cmake complains about liboqs.a not existing, before the liboqs project can be built. I don't know
if there's another way of expressing this so that liboqs.a's existence is checked later, so perhaps
so other way of making this behave correctly.

2021-08-03 14:36 UTC, hannestschofenig commented
Adding the liboqs.a library alone will not be enough to add support for PQC algorithms to the TLS 1.3 implementation. Do you agree?

2021-08-03 15:43 UTC, brett-warren-arm commented
Yes, a new module will need to be added to mbedtls to integrate the PQC algorithms into the key schedule.

2021-08-03 16:15 UTC, hanno-arm commented
@hannestschofenig We're meeting once a week to discuss the steps ahead - do you want to join?

2021-08-06 10:34 UTC, hanno-arm commented on 3rdparty/liboqs/CMakeLists.txt
> +	CMAKE_CACHE_ARGS           -DOQS_USE_OPENSSL:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_BINARY_DIR}
```suggestion
	CMAKE_CACHE_ARGS           -DOQS_ENABLE_KEM_CLASSIC_MCELIECE:BOOL=OFF -DOQS_USE_OPENSSL:BOOL=OFF** -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_BINARY_DIR}
```
Adding that to resolve some compilation issues, which at least I have trying to build classic McEliece for AVX2.

2021-08-06 10:36 UTC, hanno-arm commented on programs/CMakeLists.txt
> +#add_subdirectory(aes)
Why were those things commented out?

2021-08-06 10:36 UTC, hanno-arm commented on programs/ssl/CMakeLists.txt
> -set_property(TARGET ssl_client2 APPEND PROPERTY SOURCES
Why?

2021-08-06 11:19 UTC, hanno-arm requested changes
@brett-warren-arm The build is failing when `MBEDTLS_LIBOQS_ENABLED` is unset. It looks like the addition of liboqs as a library dependency should be conditional on that option being set. Can you fix that.

Also, something seems wrong with checking whether a re-build of liboqs is necessary -- on my machine, every `make` triggers an entire rebuild. Can you also look into that?

Otherwise, the PR is good to go.

2021-08-08 19:41 UTC, brett-warren-arm commented
Commits mitigating the two above issues have been pushed, so this PR should now be completely ready

2021-08-09 05:11 UTC, hanno-arm approved these changes
Thanks @brett-warren-arm -- I confirm this works. There are probably things that can be improved here, e.g. avoiding re-calling `cmake` upon changes of `mbedtls_config.h`, or supporting plain `make`, but for our purpose this is good enough as a start.

2021-08-09 05:11 UTC, merged