Send pending alert after ssl_server_hello_process
hannestschofenig/mbedtls pull request #78
Opened 2020-12-08 15:22 UTC by lhuang04

Summary:
`ssl_server_hello_process` may call `ssl_server_hello_coordinate`, and
other subroutines, they may setup pending alerts by
SSL_PEND_FATAL_ALERT.
These pending alerts may not be fired as we return early before we call
[mbedtls_ssl_handle_pending_alert](https://github.com/hannestschofenig/mbedtls/blob/tls13-prototype/library/ssl_tls13_client.c#L4477)

Test Plan:
Send corrupted server hello, verify the unexpected message alert is
fired.

Test Plan:
Send corrupted server hello, verify the unexpected message alert is
fired.

Reviewers:
hanno.becker@arm.com,hannes.tschofenig@arm.com,junqi.wang@live.com,zhi.han@gmail.com

Subscribers:

Tasks:

Tags:

2021-01-04 07:34 UTC, hanno-arm requested changes
Good catch @lhuang04 :+1: 

Two suggestions:
* There are other places in the client-side handshake state machine loop where we `return` upon a failure, instead of `break`ing the loop. Those places may also lead to the loss of alerts. Would you mind adjusting them as well?
* We might want to add a test for this in `ssl-opt.sh`, grepping for some debug output witnessing the receipt of a fatal alert on the server-side. I don't know from the top of my head what easy mismatching configurations we could use on server/client to trigger this, though - would you mind taking a look?

2021-01-08 18:52 UTC, lhuang04 commented
* Changed all the `break` to `return` for all cases in `mbedtls_ssl_handshake_client_step` for all cases that may have a potential pending alert. 
@hanno-arm , could take another look?
Regarding the test, I can't find any example that check if server receives alert in `ssl-opt.sh` . I searched `got an alert message, type:  in the script`, there is no one use the pattern of `-s`.

2021-01-19 15:11 UTC, lhuang04 commented
@hanno-arm , I managed found one test case that client may send alert after receiving server hello msg (listed in the following patch). However it turns out to be server side #126 , #127. I'd rather fix those issues, instead of adding such test case.

```
diff --git a/tests/ssl-opt.sh b/tests/ssl-opt.sh
index e01c09a59..94f2ebbbe 100755
--- a/tests/ssl-opt.sh
+++ b/tests/ssl-opt.sh
@@ -1530,6 +1530,19 @@ run_test    "TLS 1.3, TLS_AES_256_GCM_SHA384, ext PSK, early data status - accep
             0 \
      -c "early data status = 2"  \

+# mismatched group and exchange modes
+requires_config_enabled MBEDTLS_SSL_PROTO_TLS1_3_EXPERIMENTAL
+requires_config_enabled MBEDTLS_DEBUG_C
+run_test    "TLS 1.3, TLS_AES_128_CCM_SHA256 with mismatched group and exchange mode" \
+            "$P_SRV debug_level=5 force_version=tls1_3 key_exchange_modes=ecdhe_ecdsa named_groups=secp256r1" \
+            "$P_CLI debug_level=5 force_version=tls1_3 server_name=localhost force_ciphersuite=TLS_AES_128_CCM_SHA256 key_exchange_modes=psk_dhe key_share_named_groups=secp521r1" \
+            1 \
+            -s "no matching curve for ECDHE"            \
+            -s "write hello retry request"              \
+            -c "received HelloRetryRequest message"     \
+            -c "bad hello retry request message"        \
+            -c "send alert message"
+
 #
 # TLS 1.2 specific tests
 #
```

2021-01-28 05:56 UTC, hanno-arm approved these changes

2021-01-28 05:56 UTC, merged