Tls13 prototype compile out srv
hannestschofenig/mbedtls pull request #79
Opened 2020-12-08 17:19 UTC by lhuang04

2021-01-04 08:09 UTC, hanno-arm commented
Partial fix to https://github.com/hannestschofenig/mbedtls/issues/98

2021-01-04 08:15 UTC, hanno-arm commented on library/ssl_tls13_generic.c
> +    sig_alg_list_size = ( ( buf[0] << 8 ) | ( buf[1] ) );
Upstream Mbed TLS has recently moved to C99, but nonetheless most if not all of the code puts variable declarations at the beginning of scopes, which isn't the case with this change if `MBEDTLS_SSL_SRV_C` is defined. Could you adapt the code in a way that keeps declarations at the top of the scope?

2021-01-04 08:16 UTC, hanno-arm commented on library/ssl_tls13_generic.c
> +#if defined(MBEDTLS_SSL_SRV_C)
This change leads to a compile-time error because the `sig_alg` variable is now set but not used.

2021-01-04 08:43 UTC, hanno-arm requested changes
@lhuang04 Could you elaborate on the rationale for this change?

It seems to me that we need to parse the signature algorithms extensions both on the server and on the client side, because it may appear in either the client's `ClientHello` or in the server's `CertificateRequest`. This suggests that it shouldn't be guarded by either of `MBEDTLS_SSL_{CLI|SRV}_C`.

If we introduce a compile-time option to control client-side authentication at some point, we may refine this to a guard by `MBEDTLS_SSL_SRV_C || ( MBEDTLS_SSL_CLI_C && MBEDTLS_SSL_CLIENT_AUTHENTICATION )`, but until then I think it has to be unconditional.

2021-01-05 15:58 UTC, lhuang04 commented
@hanno-arm, thanks for reviewing it. This PR is no longer needed as #62 had move `received_signature_schemes_list` out of the `MBEDTLS_SSL_SRV_C`. `received_signature_schemes_list` is used in both client and server mode.

2021-01-05 15:58 UTC, closed without merging